# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.elasticsearch:
        class: Elasticsearch\ClientBuilder
        factory: [AppBundle\Factories\ElasticsearchClientBuilderFactory, build]
        arguments: ["%elasticsearch_cluster%"]
    app.data:
        class: AppBundle\Service\DataService
        arguments: ["@app.elasticsearch"]
